import { describe, it, expect, vi, beforeEach } from 'vitest';
import { PaymentRecordingService } from '../../services/PaymentRecordingService';

vi.mock('../../repositories/PaymentRecordingRepository', () => ({
  default: {
    generateZReport: vi.fn(),
    getZReport: vi.fn(),
    getZReportsByDateRange: vi.fn(),
    updateZReportNotes: vi.fn(),
  },
}));

import PaymentRecordingRepository from '../../repositories/PaymentRecordingRepository';

describe('PaymentRecordingService - Z-Report', () => {
  let service: PaymentRecordingService;

  beforeEach(() => {
    vi.clearAllMocks();
    service = new PaymentRecordingService();
  });

  it('should generate a Z-report for a valid past date', async () => {
    const mockReport = {
      id: 'zr-1',
      salon_id: 'salon-1',
      report_date: '2024-01-15',
      total_cash: 5000,
      total_upi: 3000,
      total_card: 2000,
      total_phonepe: 1000,
      total_other: 0,
      total_amount: 11000,
      transaction_count: 25,
      generated_by: 'user-1',
    };
    vi.mocked(PaymentRecordingRepository.generateZReport).mockResolvedValue(mockReport);

    const result = await service.generateZReport('salon-1', '2024-01-15', 'user-1');

    expect(result.total_amount).toBe(11000);
    expect(result.transaction_count).toBe(25);
    expect(PaymentRecordingRepository.generateZReport).toHaveBeenCalledWith('salon-1', '2024-01-15', 'user-1');
  });

  it('should throw 400 when generating report for future date', async () => {
    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 10);
    const futureDateStr = futureDate.toISOString().split('T')[0];

    await expect(service.generateZReport('salon-1', futureDateStr, 'user-1'))
      .rejects.toThrow('Cannot generate report for future dates');
  });

  it('should throw 400 for invalid date format', async () => {
    await expect(service.generateZReport('salon-1', '15-01-2024', 'user-1'))
      .rejects.toThrow('Invalid date format');
  });

  it('should throw 400 when required fields are missing', async () => {
    await expect(service.generateZReport('', '2024-01-15', 'user-1'))
      .rejects.toThrow('Salon ID, report date, and generated by are required');
  });

  it('should get Z-report by date', async () => {
    const mockReport = {
      id: 'zr-1',
      salon_id: 'salon-1',
      report_date: '2024-01-15',
      total_amount: 11000,
    };
    vi.mocked(PaymentRecordingRepository.getZReport).mockResolvedValue(mockReport);

    const result = await service.getZReport('salon-1', '2024-01-15');
    expect(result).toEqual(mockReport);
  });

  it('should return null when Z-report not found', async () => {
    vi.mocked(PaymentRecordingRepository.getZReport).mockResolvedValue(null);

    const result = await service.getZReport('salon-1', '2024-01-15');
    expect(result).toBeNull();
  });

  it('should get Z-reports by date range', async () => {
    const mockReports = [
      { id: 'zr-1', report_date: '2024-01-15', total_amount: 11000 },
      { id: 'zr-2', report_date: '2024-01-16', total_amount: 9500 },
    ];
    vi.mocked(PaymentRecordingRepository.getZReportsByDateRange).mockResolvedValue(mockReports);

    const result = await service.getZReportsByDateRange('salon-1', '2024-01-15', '2024-01-16');
    expect(result).toHaveLength(2);
  });

  it('should throw 400 when start date is after end date', async () => {
    await expect(service.getZReportsByDateRange('salon-1', '2024-01-16', '2024-01-15'))
      .rejects.toThrow('Start date must be before end date');
  });

  it('should throw 400 for invalid date format in range query', async () => {
    await expect(service.getZReportsByDateRange('salon-1', 'invalid', '2024-01-15'))
      .rejects.toThrow('Invalid date format');
  });
});
